
package com.learnwebservices.services.tempconverter;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TempConverterEndpointService", targetNamespace = "http://learnwebservices.com/services/tempconverter", wsdlLocation = "http://www.learnwebservices.com/services/tempconverter?wsdl")
public class TempConverterEndpointService
    extends Service
{

    private final static URL TEMPCONVERTERENDPOINTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.learnwebservices.services.tempconverter.TempConverterEndpointService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.learnwebservices.services.tempconverter.TempConverterEndpointService.class.getResource(".");
            url = new URL(baseUrl, "http://www.learnwebservices.com/services/tempconverter?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.learnwebservices.com/services/tempconverter?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TEMPCONVERTERENDPOINTSERVICE_WSDL_LOCATION = url;
    }

    public TempConverterEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TempConverterEndpointService() {
        super(TEMPCONVERTERENDPOINTSERVICE_WSDL_LOCATION, new QName("http://learnwebservices.com/services/tempconverter", "TempConverterEndpointService"));
    }

    /**
     * 
     * @return
     *     returns TempConverterEndpoint
     */
    @WebEndpoint(name = "TempConverterEndpointPort")
    public TempConverterEndpoint getTempConverterEndpointPort() {
        return super.getPort(new QName("http://learnwebservices.com/services/tempconverter", "TempConverterEndpointPort"), TempConverterEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TempConverterEndpoint
     */
    @WebEndpoint(name = "TempConverterEndpointPort")
    public TempConverterEndpoint getTempConverterEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://learnwebservices.com/services/tempconverter", "TempConverterEndpointPort"), TempConverterEndpoint.class, features);
    }

}
